apiVersion: apps/v1
kind: Deployment
metadata:
   name: keycloak-showcase-deployment
spec:
   replicas: 3
   selector:
      matchLabels:
         app: keycloak-showcase
   minReadySeconds: 10
   strategy:
      type: RollingUpdate
      rollingUpdate:
         maxUnavailable: 1
         maxSurge: 1
   template:
      metadata:
         labels:
            app: keycloak-showcase
      spec:
         containers:
         - name: keycloak-showcase
           image: gunnaraccso/camunda-showcase-keycloak:1.3.0-SNAPSHOT
           ports:
           - containerPort: 8080
           env:
           - name: JDBC_URL
             value: jdbc:postgresql://postgres-service:5432/camunda
           - name: JDBC_USER
             value: camunda
           - name: JDBC_PASSWORD
             value: camunda1!
           - name: KEYCLOAK_URL_AUTH
             value: http://armstrong02
           - name: KEYCLOAK_URL_TOKEN
             value: http://keycloak-server-service:8080
           - name: KEYCLOAK_URL_PLUGIN
             value: https://keycloak-server-service:8443
           - name: KEYCLOAK_CLIENT_ID
             value: camunda-identity-service
           - name: KEYCLOAK_CLIENT_SECRET
             value: 0ca35c49-c721-44dd-a6c2-a5e825e13c84
         hostAliases:
         - ip: 10.0.75.1
           hostnames:
           - armstrong02
# Redis Session Cache not yet in use
#           - name: SESSION_STORE_TYPE
#             value: redis
#           - name: REDIS_HOST
#             value: redis-service