spring.datasource:
  url: ${JDBC_URL:jdbc:h2:./camunda-db;DB_CLOSE_DELAY=-1;MVCC=TRUE;DB_CLOSE_ON_EXIT=FALSE}
  username: ${JDBC_USER:sa}
  password: ${JDBC_PASSWORD:sa}
#spring.h2.console.enabled: true

spring:
  jersey:
    application-path: /engine-rest

# Redis Session Cache not yet in use
#  session:
#    store-type: ${SESSION_STORE_TYPE:none}
#    redis.flush-mode: immediate
#  redis:
#    host: ${REDIS_HOST:localhost}
#    port: ${REDIS_PORT:6379}

camunda.bpm:
  history-level: audit
  authorization:
    enabled: true
  filter:
    create: All tasks

server:
  port: 8080
  servlet.context-path: /camunda

keycloak.url.client: ${KEYCLOAK_URL_CLIENT:http://localhost:9000}
keycloak.url.token: ${KEYCLOAK_URL_TOKEN:http://localhost:9000}
keycloak.url.plugin: ${KEYCLOAK_URL_PLUGIN:https://localhost:9001}

security:
  oauth2:
    client:
      client-id: camunda-identity-service
      client-secret: 0ca35c49-c721-44dd-a6c2-a5e825e13c84
      accessTokenUri: ${keycloak.url.token}/auth/realms/camunda/protocol/openid-connect/token
      userAuthorizationUri: ${keycloak.url.client}/auth/realms/camunda/protocol/openid-connect/auth
      scope: openid profile email
    resource:
      userInfoUri: ${keycloak.url.client}/auth/realms/camunda/protocol/openid-connect/userinfo

logging.level.org.springframework.security: DEBUG

plugin.identity.keycloak:
  keycloakIssuerUrl: ${keycloak.url.plugin}/auth/realms/camunda
  keycloakAdminUrl: ${keycloak.url.plugin}/auth/admin/realms/camunda
  clientId: camunda-identity-service
  clientSecret: 0ca35c49-c721-44dd-a6c2-a5e825e13c84
  useEmailAsCamundaUserId: true
  useUsernameAsCamundaUserId: false
  useGroupPathAsCamundaGroupId: true
  administratorGroupName: camunda-admin
  disableSSLCertificateValidation: true